### ISSUE TITLE
"Show Current Module" not responding

### ISSUE THREAD

**Issue by CompuIves** [cerebral/codesandbox-client#26]
<img width="119" alt="screen shot 2017-12-25 at 12 59 09" src="https://user-images.githubusercontent.com/587016/34339369-80ddb2ee-e973-11e7-8dcc-c552e8c758ff.png">

It seems like this button doesn't work when clicked. Its functionality is to switch between 2 modes: project mode is when the main file is executed, current module mode is when the opened module gets executed. It kind of changes the entry point based on the mode.

**Comment by christianalfoni** [comment]
Fixed here: https://github.com/cerebral/codesandbox-client/pull/29
