### ISSUE TITLE
Tabs are gone after a fork

### ISSUE THREAD

**Issue by CompuIves** [cerebral/codesandbox-client#27]
When you fork a sandbox all tabs disappear, I think it should at least have one tab open.

<img width="1125" alt="screen shot 2017-12-25 at 13 01 44" src="https://user-images.githubusercontent.com/587016/34339393-ca85420e-e973-11e7-8312-199ba7101a3c.png">

**Comment by CompuIves** [comment]
Maybe a solution would be to store the tabs in the sandbox, the tabs seem to be sandbox specific. Or an alternative would be to store the tabs by module shortid, those stay the same between forks. I'm not sure what happens when you open a new sandbox from the profile page then though.

**Comment by christianalfoni** [comment]
Yeah, lets us just use shortid instead :) Will fix now

**Comment by christianalfoni** [comment]
Fixed in this PR: https://github.com/cerebral/codesandbox-client/pull/29

**Comment by CompuIves** [comment]
Sounds good! I'm curious what happens with this flow: open sandbox, go to search, open other sandbox. Are the tabs resetted between loaded sandboxes?
