### ISSUE TITLE
Deleting a module throws an error

### ISSUE THREAD

**Issue by CompuIves** [cerebral/codesandbox-client#28]
I received an error when I tried to delete a module:

<img width="1280" alt="screen shot 2017-12-25 at 13 02 47" src="https://user-images.githubusercontent.com/587016/34339410-fe2845a2-e973-11e7-8710-787befda7eba.png">

**Comment by christianalfoni** [comment]
Fixed in PR: https://github.com/cerebral/codesandbox-client/pull/29
