### ISSUE TITLE
Clicking code in preview should open new module

### ISSUE THREAD

**Issue by CompuIves** [cerebral/codesandbox-client#84]
When you have an error in the Preview window you can see the code where the error is. When you click that code the related module should open.

This happens because of `preview-actions`, the preview window sends out an event for `open-module`.

**Comment by christianalfoni** [comment]
Fixed in: https://github.com/cerebral/codesandbox-client/pull/89/commits/83755abb2adde155c7d11f326b0c66cb92615c0f

**Comment by christianalfoni** [comment]
Okay, in PR
